### ISSUE TITLE
非常好看的主题，但有些问题

### ISSUE THREAD

**Issue by sodading** [KeNorizon/typecho-theme-icarus#10]
主题架构和一般不同，想修改些文件找不到，能麻烦添加备注吗？

**Comment by imkero** [comment]
> 以下是主题设置中可供自定义的位点

- `<head>` 与 `</head>` 之间：设置外观 - `页头` - `<head> 标签内追加内容`
- 页脚左侧 Copyright 文本后：设置外观 - `页脚` - `页脚左侧追加内容`
- 页脚左侧 Copyright 文本后：设置外观 - `页脚` - `页脚左侧追加内容`
- `</body>` 之前：设置外观 - `页脚` - `页末追加脚本`
<br>

> 以下是输出页面 HTML 的一些相关文件
### 公共部分
- 页面头部（从 `<html>` 至 `<main>`）：`component/header.php`
- 页脚（从 `<footer>` 至 `</html>`）：`component/footer.php`

### Widget
`library/Module` 目录下 `Profile.php` 、`Toc.php` 等文件

### 文章列表及文章正文
`library/Module/Single.php`

### 评论
`library/Module/Comment.php`

### 代码中没有出现的文字
代码中通过调用 `_IcT()` 或 `_IcTp()` 函数输出的可翻译文本，可以修改 i18n 语言文件 `lang/zh_CN.php`

### 独立页面模板
归档：`page/archives.php`
分类：`page/categories.php`
标签：`page/tags.php`

<br>

一开始该项目只是自用，而且为了整理代码和适配 Widget 和 i18n 的灵活性，舍弃了常规的主题文件结构，造成了二次修改的不便，如有疑问，可以继续询问。

**Comment by sodading** [comment]
TOC Widget 在什么情况下会出现？已经在主题设置中启用，凸显文字使用了h1

**Comment by imkero** [comment]
> TOC Widget 在什么情况下会出现？已经在主题设置中启用，凸显文字使用了h1

你好，根据 Markdown 使用习惯，大标题（即 Typecho 中的文章标题）对应 `<h1>` ，因此 TOC Widget 只识别对应于 `<h2>` - `<h6>` 的标题。如果你的文章中全部使用 `<h1>` 标题，会被视作文章中无任何标题而自动隐藏 TOC Widget。

你可以将各级标题均增加一级（如 `<h1>` 改为 `<h2>`），或对 `library/Module/Toc.php` 作以下相应改动。（修改的部分是正则表达式以及对 `$depth` 变量赋值的代码）

```php
        $content = preg_replace_callback(
            '/<h([1-6])(|\s[^>]*)>(.*?)<\/h\1>/i', 
            function ($matches) use(&$tocNumStack) {
                $tocIndex = count(self::$_toc) - 1;
                $depthCounter = count($tocNumStack);
                
                $depth = intval($matches[1]);
```
