### ISSUE TITLE
请问一下css样式应该在哪里改？

### ISSUE THREAD

**Issue by ZAESKY** [KeNorizon/typecho-theme-icarus#11]
想修改一下css样式，但是发现是托管的文件，应该怎么修改样式？

**Comment by imkero** [comment]
你好。本主题的 CSS 样式由 Bulma CSS 框架等**外部样式**及本主题**内部样式**两部分组成。内部样式可以覆盖外部样式。

如需修改内部样式，直接修改本主题样式文件 `/usr/themes/icarus/assets/css/style.css` 即可。
如需修改外部样式，可以在本主题样式文件 `/usr/themes/icarus/assets/css/style.css` 中，添加相同的 CSS 选择器的样式，从而覆盖原有样式。

另外也可以在 Typecho 后台的 `网站外观` - `设置外观` - `页头` - `<head> 标签内追加内容` 一栏，添加一个 `<style>` 标签以追加 CSS 样式。此种方法可以修改上述两种样式。
