### ISSUE TITLE
建议(侧边栏)

### ISSUE THREAD

**Issue by qine233** [KeNorizon/typecho-theme-icarus#12]
有时候文章太长了，pc端浏览的话，侧边栏理应跟着浏览位置上下浮动

**Comment by imkero** [comment]
你好，如果需要让侧边栏固定（即不跟随页面一同滚动）的话，在 `Typecho 后台 - 外观 - 设置外观 - 侧边栏` 中，根据需要启用“固定左边栏”和（或） “固定右边栏”即可。
![设置外观-侧边栏-侧边栏固定](https://user-images.githubusercontent.com/32296555/77992699-2ea3ed00-7359-11ea-9349-0dfed4e23d47.png)

**Comment by qine233** [comment]
好的
