### ISSUE TITLE
希望可以修改背景

### ISSUE THREAD

**Issue by CmmmmmmLau** [KeNorizon/typecho-theme-icarus#15]
希望能支持把纯白的背景改成图片

**Comment by imkero** [comment]
您好，如果需要修改页面的背景的话，可以通过增加 CSS 样式来实现。
Icarus 主题支持在页面头部插入自定义的 HTML 代码。具体来说，插入一对 `<style>` 标签，在其中写入设置页面背景的 CSS 样式即可。

在页面头部插入 HTML 代码的步骤如下：
1. 登录 Typecho 博客后台
2. 选择【控制台】>【外观】>【设置外观】
3. 找到【页头】>【`<head>` 标签内追加内容】
4. 在输入框中增加以下内容

设置页面背景为图片的参考代码，请按照实际需要进行调整：
```html
<style>
body {
  background-image: url(背景图片URL);
  background-size: cover;
  background-attachment: fixed;
}
</style>
```
