### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by madlifer** [KeNorizon/typecho-theme-icarus#3]
- 导航栏太空了，建议增加说说这种类型，类似handsome主题
- 最新文章条数建议增加可显示数量，目前10条有点太多了

**Comment by imkero** [comment]
感谢建议。
1. typecho-theme-icarus 是一个从 Hexo 主题导出的 Typecho 主题项目，master 分支版本会尽量保留主题的原貌。而且目前还在搬运阶段，主要进行的工作是将原主题的功能和细节进行复刻。说说等增强功能会在搬运完成后新建一个分支进行开发。
2. 最新文章条数考虑到 Typecho 原生设置中有这一个设置项（postsListSize）（位于 设置-阅读-文章列表数目），因此直接调用了这个设置项的数值作为侧边栏最新文章 Widget 的条目数。这个设置项的默认值是 10。在最新文章 Widget 的描述中也有相关指引。考虑到这个设置项比较难找到，打算改为在主题设置中提供条目数自定义的功能。

**Comment by imkero** [comment]
感谢建议。
1. typecho-theme-icarus 是一个从 Hexo 主题导出的 Typecho 主题项目，master 分支版本会尽量保留主题的原貌。而且目前还在搬运阶段，主要进行的工作是将原主题的功能和细节进行复刻。说说等增强功能会在搬运完成后新建一个分支进行开发。
2. 最新文章条数考虑到 Typecho 原生设置中有这一个设置项（postsListSize）（位于 设置-阅读-文章列表数目），因此直接调用了这个设置项的数值作为侧边栏最新文章 Widget 的条目数。这个设置项的默认值是 10。在最新文章 Widget 的描述中也有相关指引。考虑到这个设置项比较难找到，打算改为在主题设置中提供条目数自定义的功能。

**Comment by madlifer** [comment]
好的，期待你的作品

**Comment by imkero** [comment]
842768b825984c77999decb2e4a4cfddf69d63f7 已增加最新文章的显示数量自定义，默认值为显示5篇。
