### ISSUE TITLE
可以分享一下archives.html和categories.html吗？

### ISSUE THREAD

**Issue by 1491608972** [KeNorizon/typecho-theme-icarus#4]
看不懂代码……

**Comment by imkero** [comment]
你好，要使用归档页面和分类页面的话，需要在 Typecho 后台中新建两个**独立页面**（撰写 - 创建页面）。缩略名分别为 `archives` 和 `categories` 即可。
![Icarus 内置页面创建指引](https://user-images.githubusercontent.com/32296555/55492094-35762200-5669-11e9-9b9c-1bf150cf92ef.png)

**Comment by 1491608972** [comment]
谢谢，刚用这个还没来得及细看

**Comment by imkero** [comment]
commit e57e5c3fe2d966ce0a1f2784f516bf4ff0e7da90 增加了对主题内置的 `分类` 、 `归档` 和 `标签` 页面的创建指引。感谢提出使用过程中的问题。
![theme-based page guidance](https://user-images.githubusercontent.com/32296555/55537236-5765b800-56ee-11e9-9783-304d685e58bf.png)
