### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by afeigorgor** [KeNorizon/typecho-theme-icarus#6]
在文章或页面使用表格(如下)，如果xxx过长的话，会超出布局，并且继续显示在右侧栏后面
```
| <center>标题</center> | <center>标题</center> |
| --------------------- | ----------------------|
| 内容 | xxxxxxxxxxxxxxxxxxx |
```

**Comment by imkero** [comment]
感谢反馈。

出现这个问题的原因是，浏览器对 `<table>` 表格的默认渲染行为，在少数情况下是不符合预期的。如您举例的表格中，第二行第二列有一个长单词 `xxxxxxxxxxxxxxx`，默认情况下 ( `word-break: ?` ) ，浏览器会将其视作一个不可分割的单词而不做折行处理，因而会强行增加表格的宽度。

由于表格中的内容多种多样（中文、英文、图片、代码等），因此不适宜在主题的样式表中直接进行相关的设定。建议在需要指定表格的展示细节（如各列的宽度等）时，使用 HTML 代码而不是 Markdown 向文章或者页面中添加表格，以便合适地呈现表格的内容。

如果确实需要展示您所举例的这种内容，下面给出若干解决方法供参考，请按需要选用。

1. 强行折行（可能会影响西文的展示）
```html
<table style="word-break: break-word;">
    <tbody>
        <tr>
            <td>short string</td>
            <td>looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong string</td>
        </tr>
    </tbody>
</table>
```

2. 内嵌滚动条
```html
<table style="table-layout:fixed;">
    <tbody>
        <tr>
            <td>short string</td>
            <td style="overflow: auto;">looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong string</td>
        </tr>
    </tbody>
</table>
```

### 详见
1. https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break
2. https://css-tricks.com/fixing-tables-long-strings/

**Comment by afeigorgor** [comment]
谢谢你的恢复指导，已经按你教的方法改了。题外话：不过我在使用默认主题时，它好像是自动折行的。
