### ISSUE TITLE
保存配置出现错误

### ISSUE THREAD

**Issue by coolf** [KeNorizon/typecho-theme-icarus#7]
保存配置 ，显示 Database Query Error

**Comment by imkero** [comment]
比较幸运地复现了本 Issue 所描述的情况。

## 现象
- 启用主题时报错 `Database Query Error` ，但主题能够成功启用。
- 保存主题配置时报错 `Database Query Error` ，且主题配置不能成功保存。

## 日志
```
[22-Jul-2019 15:55:48 Asia/Shanghai] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1
```

## 分析
- Typecho 记录当前主题的方式为：更改 `options` 表中 `name = "theme"` 的行，设置其 `value` 为主题的目录名。
- Typecho 存储当前主题的设置项的方式为：将主题设置项数组的序列化字符串作为 `value`，存储在 **`name = "theme:主题目录名"`** 的行中。
- Typecho 的 `options` 表的 **`name` 列的最大长度为 32**

## 结论
当主题目录名（`/usr/themes/<主题目录名>/`）的长度大于 26 时（比如 `typecho-theme-icarus-master`），由于主题设置项（`options` 表中 `name = "theme:主题目录名"` 的行）不能正常保存，导致出现上述异常现象，以及不能正常启用及使用该主题。

## 解决方案
1. 切换至其他主题
2. 重命名出现问题的主题的目录名，使其长度小于等于 26
3. 重新切换至该主题
